const ADD_STORY = "ADD_STORY";
const ADD_STORIES = "ADD_STORIES";
const UPDATE_STORY = "UPDATE_STORY";
const DELETE_STORY = "DELETE_STORY";
const DELETE_STORIES = "DELETE_STORIES";

export { ADD_STORY, ADD_STORIES, UPDATE_STORY, DELETE_STORY, DELETE_STORIES };
